Use _private_bucket for reports' storage place
viur-framework/viur-toolkit pull request #19
Opened 2024-09-27 15:20 UTC by skoegl

For now it's intended to save reports into the private bucket.

This PR is related to PRs from viur-core : https://github.com/viur-framework/viur-core/pull/1266 and https://github.com/viur-framework/viur-core/pull/1268

2024-09-30 07:51 UTC, ArneGudermann approved these changes

2024-09-30 10:30 UTC, phorward submitted a review, later dismissed

2024-10-01 15:26 UTC, sveneberth requested changes
Well, now it works for viur-core>=3.7, but no longer for viur-core=3.6. There must be a case distinction with version check.

2024-10-16 22:19 UTC, sveneberth approved these changes

2024-10-16 22:28 UTC, sveneberth approved these changes

2024-10-16 23:05 UTC, phorward approved these changes

2024-10-18 14:55 UTC, merged